// Auto-generated RU → UZ translation map
// 274 entries
export const RU_TO_UZ: Record<string, string> = {
  "База знаний": "Bilim bazasi",
  "Помощь": "Yordam",
  "Кейсы": "Keyslar",
  "Войти": "Kirish",
  "Зарегистрироваться": "Ro'yxatdan o'tish",
  "2 000+ магазинов уже подключили TGShop": "2 000+ do'kon allaqachon TGShop'ni ulagan",
  "Telegram-магазин и чаты с клиентами в одном кабинете": "Telegram-do'kon va mijozlar bilan chatlar — bitta kabinetda",
  "Ваши менеджеры не успевают отвечать всем клиентам в Telegram — и заказы уходят к конкурентам.": "Menejerlaringiz Telegramdagi barcha mijozlarga javob berishga ulgurmayapti — va buyurtmalar raqobatchilarga ketayapti.",
  "С TGShop ни одна заявка не потеряется, и клиенты смогут покупать в 1 клик.": "TGShop bilan birorta ham so'rov yo'qolmaydi, mijozlar esa 1 bosishda xarid qila oladi.",
  "Попробовать бесплатно": "Bepul boshlash",
  "14 дней бесплатно · без разработки": "14 kun bepul · dasturchilarisiz",
  "Чаты": "Chatlar",
  "Новые": "Yangi",
  "Открыты": "Ochiq",
  "Закрыты": "Yopiq",
  "Запуск за 15 минут без программистов": "15 daqiqada ishga tushiring — dasturchilarsiz",
  "новых заказов сегодня": "yangi buyurtma bugun",
  "новых заявок в чатах": "yangi so'rov chatlarda",
  "Нам доверяют": "Bizga ishonishadi",
  "x2 клиентов": "x2 mijozlar",
  "рост продаж": "onlayn savdo o'sishi",
  "товаров в заказе за квартал": "buyurtmadagi mahsulotlar chorak davomida",
  "бренд одежды, обуви и аксессуаров": "kiyim, poyabzal va aksessuarlar brendi",
  "0 сум на рекламу": "0 so'm reklama",
  "заказов с TGShop за 6 месяцев": "buyurtma TGShop bilan 6 oy ichida",
  "заказов «до» было на маркетплейсе": "buyurtma «ilgari» marketplace'da",
  "цветочный магазин": "gul do'koni",
  "Постоянный рост": "Doimiy o'sish",
  "конверсия продаж": "sotuv konversiyasi",
  "рост в месяц": "CR o'sishi oyda",
  "клиентов активировали в месяц": "mijoz faollashtirildi oyda",
  "магазин кроссовок": "krossovkalar do'koni",
  "Без сложной CRM": "Murakkab CRM'siz",
  "рост выручки": "daromad o'sishi",
  "клиентов активировали за полгода": "mijoz faollashtirildi yarim yil ichida",
  "магазин одежды": "kiyim do'koni",
  "2 000+ магазинов в Telegram": "2 000+ Telegramdagi do'konlar",
  "1,5 млн заказов обработано": "1,5 mln qayta ishlangan buyurtmalar",
  "15 минут на подключение": "15 daqiqa ulash uchun",
  "Каждый день ваш магазин теряет выручку": "Har kuni do'koningiz daromad yo'qotmoqda",
  "Клиент остался без ответа": "Mijoz javovsiz qoldi",
  "Менеджер может забыть ответить — и никто это не заметит. Клиент подождал час и купил у конкурента.": "Menejer javob berishni unutishi mumkin — va hech kim buni sezmaydi. Mijoz bir soat kutib, raqobatchidan xarid qildi.",
  "Уволился менеджер — клиенты ушли с ним": "Menejer ketdi — mijozlar ham u bilan ketdi",
  "Переписка велась в личном Telegram. Кто этот клиент и чем интересовался, знает только бывший сотрудник.": "Yozishmalar shaxsiy Telegramda yuritilgan. Bu mijoz kim va nimaga qiziqgan — faqat sobiq xodim biladi.",
  "Менеджеры обещают то, чего нет": "Menejerlar yo'q narsani va'da qiladi",
  "Менеджер грубит клиенту, называет неверную цену или придумывает сроки доставки. Об этом вы узнаёте, когда клиент уже ушёл с негативом.": "Menejer mijozga qo'pol muomala qiladi, noto'g'ri narx aytadi yoki yetkazib berish muddatini o'ylab topadi. Buni siz mijoz allaqachon norozilik bilan ketganida bilib olasiz.",
  "Контроль чатов с клиентами": "Mijozlar bilan chatlarni nazorat qilish",
  "Руководитель открывает любой диалог и видит, как менеджер обрабатывает заявки и как общается с клиентами.": "Rahbar istalgan suhbatni ochib, menejer so'rovlarni qanday qayta ishlayotganini va mijozlar bilan qanday muloqot qilayotganini ko'radi.",
  "Магазин принимает заказы 24/7": "Do'kon buyurtmalarni 24/7 qabul qiladi",
  "Клиенты оформляют заказ в один клик в любое время суток, а вы не теряете выручку в нерабочее время.": "Mijozlar sutkaning istalgan vaqtida 1 bosishda buyurtma beradi, siz esa ish vaqtidan tashqarida daromad yo'qotmaysiz.",
  "Без сложных CRM": "Murakkab CRM'siz",
  "Доступ к перепискам и заказам прямо в Telegram. Если менеджер уволится, клиенты останутся у вас, а не на чужом телефоне.": "Yozishmalar va buyurtmalarga to'g'ridan-to'g'ri Telegramdan kirish. Menejer ketsa — mijozlar sizda qoladi, begona telefonda emas.",
  "Посчитайте, сколько вы теряете": "Qancha yo'qotayotganingizni hisoblang",
  "Магазин получает 50 заявок в день, и хотя бы 10% теряются — это 5 потерянных клиентов ежедневно.": "Do'kon kuniga 50 ta so'rov oladi va ularning hech bo'lmaganda 10% yo'qoladi — bu kuniga 5 ta yo'qotilgan mijoz.",
  "При среднем чеке 300 000 soʻm это 1 500 000 soʻm в день. Или 45 миллионов soʻm в месяц.": "O'rtacha chek 300 000 so'm bo'lsa — bu kuniga 1 500 000 so'm. Yoki oyiga 45 million so'm.",
  "Не из-за плохого товара. Не из-за цены. Просто потому что ответили поздно — или не ответили вообще.": "Yomon mahsulot tufayli emas. Narx tufayli emas. Shunchaki kech javob berilgani — yoki umuman javob berilmagani uchun.",
  "Хочу больше продаж": "Ko'proq sotuv xohlayman",
  "Потери накапливаются каждый день": "Yo'qotishlar har kuni to'planadi",
  "ПОТЕРИ В МЕСЯЦ": "OYLIK YO'QOTISHLAR",
  "Средний магазин · 30 рабочих дней": "O'rtacha do'kon · 30 ish kuni",
  "Старт за 15 минут": "5 daqiqada boshlash",
  "Как начать работу — три шага": "Qanday ishni boshlash — uch qadam",
  "Создайте магазин": "Do'kon yarating",
  "Загрузите товары, включите доставку и оплату.": "Mahsulotlarni yuklang, yetkazib berish va to'lovni yoqing.",
  "Выдайте доступ менеджерам": "Menejerlarga kirish bering",
  "Обрабатывайте заявки и вопросы клиентов.": "So'rovlar va mijozlar savollarini qayta ishlang.",
  "Отслеживайте продажи": "Sotuvlarni kuzating",
  "Контролируйте все диалоги и заказы — в одном месте в Telegram.": "Barcha suhbatlar va buyurtmalarni — Telegramda bitta joyda nazorat qiling.",
  "Заказов сегодня": "Bugungi buyurtmalar",
  "Выручка": "Daromad",
  "Новых клиентов": "Yangi mijozlar",
  "Не просто переписки — а система продаж": "Faqat yozishmalar emas — sotuv tizimi",
  "Статусы заявок — сразу видно, кому не ответили": "So'rov statuslari — kimga javob berilmaganini darhol ko'rish",
  "Каждый чат имеет статус: «новый», «открыт» или «закрыт».": "Har bir chatda status bor: «yangi», «ochiq» yoki «yopiq».",
  "Не нужно запоминать, кому уже ответили, а кому — нет.": "Kimga javob berilganini, kimga berilmaganini eslab yurish shart emas.",
  "Новые заявки выделяются автоматически": "Yangi so'rovlar avtomatik ajratib ko'rsatiladi",
  "Отслеживайте, на какие чаты не ответили": "Qaysi chatlarga javob berilmaganini kuzating",
  "Бросили корзину → написать: товар скоро закончится": "Savatchani tashlab ketdi → xabar yozing: mahsulot tez tugaydi",
  "Не оплатили → автоматическое напоминание": "To'lov qilmadi → avtomatik eslatma",
  "Купили недавно → предложить новинки": "Yaqinda xarid qildi → yangiliklar taklif qiling",
  "Не активны 30 дней → вернуть промокодом": "30 kun faol emas → promokod bilan qaytaring",
  "Рассылки по готовым сегментам — возвращайте клиентов": "Tayyor segmentlar bo'yicha ommaviy xabarlar — mijozlarni qaytaring",
  "Сегменты собираются автоматически — на основе поведения клиента.": "Segmentlar mijoz xulq-atvoriga asoslanib avtomatik shakllanadi.",
  "Отправьте сообщение тем, кто бросил корзину, кто давно не покупал или только что оформил заказ.": "Savatchani tashlab ketganlarga, uzoq vaqt xarid qilmaganlarga yoki yaqinda buyurtma berganlarga xabar yuboring.",
  "Бросил корзину — догнать персональным сообщением": "Savatchani tashlab ketdi — shaxsiy xabar bilan quvib yeting",
  "Не оплатил — бот автоматически напомнит": "To'lov qilmadi — bot avtomatik eslatadi",
  "Купил недавно — предложить дополнение": "Yaqinda xarid qildi — qo'shimcha taklif qiling",
  "Не активен 7 / 30 дней — вернуть промокодом": "7/30 kun faol emas — promokod bilan qaytaring",
  "Готовые интеграции без разработки": "Dasturchilarisiz tayyor integratsiyalar",
  "Добавьте товары": "Mahsulotlarni qo'shing",
  "Массовый импорт из XML/XLS и по ссылке": "XML/XLS va havola orqali ommaviy import",
  "Импорт из Мойсклад, 1С, Billz": "MoySklad, 1C, Billz'dan import",
  "Добавление товаров вручную": "Mahsulotlarni qo'lda qo'shish",
  "Автоматическое обновление цен и остатков": "Narxlar va qoldiqlarni avtomatik yangilash",
  "Включите оплату и доставку": "To'lov va yetkazib berishni yoqing",
  "Курьерская доставка и самовывоз": "Kuryer yetkazib berish va o'zi olib ketish",
  "Онлайн-оплата в 1 клик": "1 bosishda onlayn to'lov",
  "Рассрочка": "Muddatli to'lov",
  "Чеки": "Cheklar",
  "Оплата наличными": "Naqd to'lov",
  "Привлекайте клиентов эффективно": "Mijozlarni samarali jalb qiling",
  "Промокоды": "Promokodlar",
  "Закрепите магазин в канале": "Do'konni kanalda mahkamlang",
  "Интеграция с Яндекс Метрикой": "Yandex Metrika integratsiyasi",
  "Рассылки и триггерные уведомления": "Ommaviy xabarlar va trigger bildirishnomalar",
  "Реферальная программа — клиенты приводят друзей": "Referral dastur — mijozlar do'stlarini taklif qiladi",
  "Управляйте заказами": "Buyurtmalarni boshqaring",
  "Интеграции с AmoCRM, Битрикс24": "AmoCRM, Bitrix24 integratsiyalari",
  "Уведомления о заказах в Telegram": "Telegramda buyurtmalar haqida bildirishnomalar",
  "Все диалоги с клиентами со статусами — в Telegram-боте": "Statuslari bilan barcha mijozlar suhbatlari — Telegram-botda",
  "TGShop Chat включён во все тарифы TGShop": "TGShop Chat barcha TGShop tariflariga kiritilgan",
  "Один тариф — магазин, диалоги со статусами, интеграции. Без скрытых доплат.": "Bitta tarif — do'kon, statusli suhbatlar, integratsiyalar. Yashirin qo'shimcha to'lovlarsiz.",
  "Помесячно": "Oylik",
  "За год · −20%": "Yillik · −20%",
  "Старт": "Start",
  "До 100 товаров · 1 активный магазин": "100 tagacha mahsulot · 1 faol do'kon",
  "Бизнес": "Biznes",
  "До 1000 товаров · до 5 активных магазинов": "1000 tagacha mahsulot · 5 tagacha faol do'kon",
  "Премиум": "Premium",
  "До 15000 товаров · до 10 активных магазинов": "15 000 tagacha mahsulot · 10 tagacha faol do'kon",
  "Диалоги с клиентами": "Mijozlar bilan suhbatlar",
  "Витрина для маркетплейсов": "Marketplace'lar uchun vitrina",
  "Каталог и товары": "Katalog va mahsulotlar",
  "Прием платежей": "To'lovlarni qabul qilish",
  "Интеграция со службами доставки": "Yetkazib berish xizmatlari bilan integratsiya",
  "Интеграция с CRM": "CRM bilan integratsiya",
  "Доступ к аналитике": "Analitikaga kirish",
  "Импорт товаров из XLS/XML": "XLS/XML'dan mahsulotlarni import qilish",
  "Рассылки": "Ommaviy xabarlar",
  "Интеграция с МойСклад / 1С": "MoySklad / 1C bilan integratsiya",
  "Периодический импорт по ссылке": "Havola orqali rejalashtirilgan import",
  "Нет возможности отключить «Сделано при помощи TGShop»": "«TGShop yordamida yaratilgan» yozuvini o'chirish imkonsiz",
  "Отсутствует реклама сервиса": "Xizmat reklamasi yo'q",
  "Приоритетная поддержка": "Ustuvor qo'llab-quvvatlash",
  "⚡ Популярный": "⚡ Mashhur",
  "Начать бесплатно": "Bepul boshlash",
  "14 дней бесплатно · карта не нужна · отмена в любой момент": "14 kun bepul · karta kerak emas · istalgan vaqtda bekor qilish",
  "Начните сегодня и перестаньте терять заказы в Telegram": "Bugun boshlang va Telegramda buyurtmalarni yo'qotishni to'xtating",
  "Каждую минуту, пока вы не подключили TGShop, кто-то из ваших клиентов не дождался ответа и ушёл к конкуренту.": "TGShop'ni ulaguningizcha o'tgan har bir daqiqada mijozlaringizdan biri javob kutmay raqobatchingizga ketmoqda.",
  "Создать Telegram-магазин бесплатно →": "Telegram-do'konni bepul yarating →",
  "14 дней бесплатно · отмена в любой момент": "14 kun bepul · istalgan vaqtda bekor qilish",
  "Все Telegram-чаты магазина в одном кабинете. Часть экосистемы TGShop.": "Do'konning barcha Telegram-chatlari bitta kabinetda. TGShop ekotizimining bir qismi.",
  "Полезные материалы": "Foydali materiallar",
  "Блог": "Blog",
  "FAQ": "FAQ",
  "Инструкции": "Ko'rsatmalar",
  "Решения": "Yechimlar",
  "Telegram-магазин": "Telegram-do'kon",
  "TGShop Узбекистан": "TGShop O'zbekiston",
  "Поддержка": "Qo'llab-quvvatlash",
  "Связаться": "Bog'lanish",
  "Политика данных": "Ma'lumotlar siyosati",
  "Правила использования": "Foydalanish qoidalari",
  "и чаты с клиентами в одном кабинете": "va mijozlar bilan chatlar — bitta kabinetda",
  "Ваши менеджеры не успевают отвечать всем клиентам в Telegram — и заказы уходят к конкурентам. С TGShop ни одна заявка не потеряется, и клиенты смогут покупать в 1 клик.": "Menejerlaringiz Telegramdagi barcha mijozlarga javob berishga ulgurmayapti — va buyurtmalar raqobatchilarga ketayapti. TGShop bilan birorta ham so'rov yo'qolmaydi, mijozlar esa 1 bosishda xarid qila oladi.",
  "Каждый чат имеет статус: «новый», «открыт» или «закрыт». Не нужно запоминать, кому уже ответили, а кому — нет.": "Har bir chatda status bor: «yangi», «ochiq» yoki «yopiq». Kimga javob berilganini, kimga berilmaganini eslab yurish shart emas.",
  "Сегменты собираются автоматически — на основе поведения клиента. Отправьте сообщение тем, кто бросил корзину, кто давно не покупал или только что оформил заказ.": "Segmentlar mijoz xulq-atvoriga asoslanib avtomatik shakllanadi. Savatchani tashlab ketganlarga, uzoq vaqt xarid qilmaganlarga yoki yaqinda buyurtma berganlarga xabar yuboring.",
  "Не из-за плохого товара — просто потому что ответили поздно.": "Yomon mahsulot tufayli emas — shunchaki kech javob berilgani uchun.",
  "Магазин": "Do'kon",
  "🛍 Магазин": "🛍 Do'kon",
  "💬 Чаты": "💬 Chatlar",
  "Заказы": "Buyurtmalar",
  "Новый": "Yangi",
  "Открыт": "Ochiq",
  "Закрыт": "Yopiq",
  "новый": "yangi",
  "открыт": "ochiq",
  "закрыт": "yopiq",
  "Каталог": "Katalog",
  "Оплата": "To'lov",
  "Доставка": "Yetkazib berish",
  "24 SKU": "24 SKU",
  "Click, Payme, наличные": "Click, Payme, naqd",
  "3 способа": "3 ta usul",
  "Заказ оформлен": "Buyurtma rasmiylashtirildi",
  "Запуск за": "Boshlash",
  "15 минут": "15 daqiqa",
  "без программистов": "dasturchilarsiz",
  "новых заказов": "yangi buyurtma",
  "сегодня": "bugun",
  "новых": "yangi",
  "заявок в чатах": "so'rov chatlarda",
  "новых сообщений": "yangi xabarlar",
  "ждёт": "kutmoqda",
  "ждёт ответа": "javob kutmoqda",
  "только что": "hozirgina",
  "1 мин": "1 daq",
  "4 мин": "4 daq",
  "5 мин": "5 daq",
  "10 мин": "10 daq",
  "12 мин": "12 daq",
  "15 мин": "15 daq",
  "23 мин": "23 daq",
  "48": "48",
  "2 мин назад": "2 daq oldin",
  "5 мин назад": "5 daq oldin",
  "23 мин назад": "23 daq oldin",
  "15 мин назад": "15 daq oldin",
  "1 мин назад": "1 daq oldin",
  "Главные функции": "Asosiy funksiyalar",
  "Бросили корзину": "Savatchani tashlab ketdi",
  "Не оплатили": "To'lov qilmadi",
  "Купили недавно": "Yaqinda xarid qildi",
  "Не активны 30 дней": "30 kun faol emas",
  "→ написать: товар скоро закончится": "→ ommaviy xabar yuborish",
  "→ автоматическое напоминание": "→ avtomatik eslatma",
  "→ предложить новинки": "→ yana sotish",
  "→ вернуть промокодом": "→ promokod berish",
  "До 1 000 товаров · до 5 активных магазинов": "1000 tagacha mahsulot · 5 tagacha faol do'kon",
  "До 15 000 товаров · до 10 активных магазинов": "15 000 tagacha mahsulot · 10 tagacha faol do'kon",
  "30 ДНЕЙ": "30 KUN",
  "день 1 — 1,5 млн": "1-kun — 1,5 mln",
  "день 30 —": "30-kun —",
  "45 млн soʻm": "45 mln so'm",
  "за квартал": "chorak davomida",
  "в месяц": "oyda",
  "за полгода": "yarim yil ichida",
  "с TGShop": "TGShop bilan",
  "с TGShop за 6 месяцев": "TGShop bilan 6 oy ichida",
  "«до» было на": "«ilgari»",
  "маркетплейсе": "marketplace'da",
  "Дилшод М.": "Dilshod M.",
  "Юлия К.": "Yuliya K.",
  "Зухра М.": "Zuhra M.",
  "Акмал Т.": "Akmal T.",
  "Мадина Х.": "Madina X.",
  "Малика О.": "Malika O.",
  "Можно в рассрочку?": "Bo'lib to'lash mumkinmi?",
  "Когда появится S?": "S o'lcham qachon paydo bo'ladi?",
  "Когда доставка?": "Yetkazib berish qachon?",
  "Уточните адрес": "Manzil?",
  "Получила 👍": "Oldim 👍",
  "Спасибо!": "Rahmat!",
  "Здравствуйте! Есть Nike Air Max 39?": "Salom! Nike bormi?",
  "Алина: Передал в доставку ✅": "Alina: Yetkazishga topshirdim ✅",
  "Есть Nike Air Max 39?": "Nike bormi?",
  "Да, 1 290 000 soʻm. Оформлять?": "Buyurtma bermoqchiman",
  "Доставите сегодня до 18:00?": "Bugun soat 18:00 gacha yetkazib berasizmi?",
  "Закрыть меню": "Menyuni yopish",
  "Открыть меню": "Menyuni ochish",
  "Все права защищены.": "Barcha huquqlar himoyalangan.",
  "5 минут": "5 daqiqa",
  "1 минута": "1 daqiqa",
  "автоматически": "avtomatik",
  "Шаг 1": "Qadam 1",
  "Шаг 2": "Qadam 2",
  "Шаг 3": "Qadam 3",
  "новых клиентов": "yangi mijoz",
  "Язык:": "Til:",
  "товаров в заказе": "buyurtmadagi mahsulotlar",
  "Fashion Fabrique": "Fashion Fabrique",
  "заказов": "buyurtma",
  "за 6 месяцев": "6 oy ichida",
  "Around You": "Around You",
  "Hold Store": "Hold Store",
  "Casher": "Casher",
  "магазинов в Telegram": "Telegramdagi do'kon",
  "заказов обработано": "buyurtma qayta ishlandi",
  "на подключение": "ulash uchun",
  "Цена бездействия": "Harakatsizlikning narxi",
  "Старт за 5 минут": "5 daqiqada boshlash",
  "Регина К.": "Regina K.",
  "Не оплатил — напомнить за 1 клик": "To'lov qilmadi — 1 bosishda eslatish",
  "1. Добавьте товары": "1. Mahsulotlarni qo'shing",
  "2. Включите оплату и доставку": "2. To'lov va yetkazib berishni yoqing",
  "3. Привлекайте клиентов эффективно": "3. Mijozlarni samarali jalb qiling",
  "4. Управляйте заказами": "4. Buyurtmalarni boshqaring",
  "МойСклад": "MoySklad",
  "Битрикс24": "Bitrix24",
  "soʻm / мес": "so'm / oy",
  "soʻm/мес": "so'm/oy",
  "499 000 soʻm/мес": "499 000 so'm/oy",
  "699 000 soʻm/мес": "699 000 so'm/oy",
  "999 000 soʻm/мес": "999 000 so'm/oy",
  "1,5 млн": "1,5 mln",
};
